### ISSUE TITLE
fluidpages version 3.1.2 crashes backend

### ISSUE THREAD

**Issue by robsonrobi** [FluidTYPO3/fluidpages#224]
hello.

we are currently using flux 7.1.2, fluidcontent 4.1.1, view 2.0 and vhs 2.2.0 and fluidpages 3.1.2.
Updating to the last version of fluidpages 3.1.2 results in strange beahviour. Pages with lots of content elements on it are not loaded in the backend anymore:

typo3/sysext/cms/layout/db_layout.php?id=77 results in an internal server error 500. 

Pages with only a few components on it are working, but the loading process takes very very long.

we switched back to version fluidpages 3.1.1 an the backend works again.

Can anyone help?

**Comment by NamelessCoder** [comment]
Would you mind doing a quick check if the `development` branch of fluidpages also does this?

And if it does: a stack dump or indication where the error happens would be of great help! ;)

**Comment by robsonrobi** [comment]
Do i need to install the dev versions of flux and fluidcontent also?

**Comment by robsonrobi** [comment]
The development version worked. But i needed FLUX to get it working, also updated fluidcontent. Editing an existing FCE and save it results in a destroyed FCE, meaning, that the element ist not configurable anymore. Existing f.e. images or text is not present anymore.

**Comment by NamelessCoder** [comment]
Hi @robsonrobi - just an update: the most recent `development` branches have received a few bug fixes and performance improvements; you should not experience the FCE issue and perhaps the performance issue may not be a factor after the improvements. We are also planning this change: https://github.com/FluidTYPO3/flux/issues/760 which should further improve the performance of all Providers to even further limit potential timeout issues. And I personally plan to write a detailed article about possible shortcuts to better performance with Flux in general - once we release version 7.2.

So you may want to update your branches again for another attempt - or wait a bit and then update so you get the `fluidpages` changes. Or as a perfectly valid option, roll back to `fluidpages` 3.1.1 to avoid the issue until you can upgrade to properly stable versions. Since you are already using Flux 7.1 the upgrade should be quite smooth with no or very little manual labor required.

I'll take the liberty of closing this issue - but if you do give the `development` branch a try and run into similar issues, we would be very happy if you could debug a little closer and maybe even determine which point of the code breaks or runs too slowly and make a pull request or just let us know what you find.

**Comment by robsonrobi** [comment]
Hello Claus, i just testet the develoment versions of the extensions. The backend is now stable, but a a sideeffect i am not able to create new pages, a network error appears. So i am waiting for FLUX 7.2 and till then i stay wit fluidpages 3.1.1.

Thank you.
