### ISSUE TITLE
Inline FAL in Page Configuration

### ISSUE THREAD

**Issue by Idleworks** [FluidTYPO3/fluidpages#228]
![pages-fal](https://cloud.githubusercontent.com/assets/6685173/6148755/62d16272-b204-11e4-8d33-9940671d093e.jpg)
First I place an inline fal field in flux' page config
```html
<flux:field.inline.fal name="images" label="Images" maxItems="99" />
```

Then I insert an image in my new field in page properties (not in the section below for subpages).
On first save, everything is ok but then my image get referenced for section subpages as well. That's kind of weird.

Problem here: TYPO3 saves the entry in sys_file_references with fieldname "images". Flexform renders that entry for both sections (current page AND subpages). Somehow that should be separated, e.g. with prefix of flexform field "tx_fed_page_flexform" and "tx_fed_page_flexform_sub".

**Comment by NamelessCoder** [comment]
Hi Philipp,

I believe this is the same issue as reported in https://github.com/FluidTYPO3/flux/issues/759 - I gave a bit of detail about what's going on and how this one should be solved. Unfortunately, the problem occurs in the deep internals of TYPO3 and we cannot (one could argue, should not) attempt to solve that via overrides as it affects *any* FlexForm implementation, not just Flux.

I'll take the liberty of closing this one and encourage to report and push for the fix in the core. Unfortunately I'm a little short on time these days and cannot take care of this one personally, but you are more than welcome to ask around in #fedext and ally yourself with other users - because you are definitely not alone with this problem!

**Comment by cweiske** [comment]
TYPO3 core bug created: [Bug #71239: FAL relation + flexform config: Use full setting path as name](https://forge.typo3.org/issues/71239).
