### ISSUE TITLE
Configuration of collections of fluidpages in TypoScript

### ISSUE THREAD

**Issue by SventB** [FluidTYPO3/fluidpages#232]
On this page (https://fluidtypo3.org/documentation/templating-manual/templating/using-templates/selecting-page-templates.html) you write:

> It is important to note here that the page templates which can be selected, are all configured by TypoScript which means you can change which templates can be selected, at any point in your page tree. You can use this to create sets of page templates which can only be used on some select subpages - for example specially branded campaign pages for a subsection of your site, without making those same templates available outside the campaign branch of pages.

But this seems not to work.

When adding this TypoScript into the **root template**, it works:

    plugin.tx_fluidpages.collections.myext {
        templateRootPath = {$plugin.myext.view.fedRootPath}/Templates/
        partialRootPath = {$plugin.myext.view.fedRootPath}/Partials/
        layoutRootPath = {$plugin.myext.view.fedRootPath}/Layouts/
    }

But when removing this TypoScript from the root template and adding it into a **TypoScript template on a subpage**, the page layouts are missing in the page properties.

I've tested this in two different systems, TYPO3 version 6.2, fluidpages version 3.1.2.

**Comment by Outdoorsman** [comment]
Don't know if this applies to your case but I just read something about legacy support being removed so you can no longer use ```plugin.tx_fluidpages.collections.*``` or ```plugin.tx_fed.page.*``` (and corresponding for Fluidcontent) to register collections. Read more about that here:
https://fluidtypo3.org/blog/news/coming-changes-in-flux-72.html

**Comment by SventB** [comment]
Thank you for the hint. But with current version, this should be possible.
And I hope for future release, that you are able to use selected page templates for different page trees, else, there will be tons of different page templates in my system, the editor can choose from but most of them should only be chooseable in specific page trees.

**Comment by NamelessCoder** [comment]
Hi @SventB - in the current version you use, only TypoScript that is added to root templates is recognised. If you upgrade to `development` or wait for 7.2 then that fact changes (because we change the ConfigurationManager TYPO3 uses), but then you also lose the ability to even define those collections. As @Outdoorsman says, you definitely should be upgrading to a provider extension soon.

If you do consider upgrading then you may want to read a bit on https://github.com/FluidTYPO3/flux/commit/8fe7e6efd1e60e81f5281e65d77343c7edf177d1 before 7.2 is released - this new feature allows you to manipulate your templates defined in extensions, by overriding TypoScript.

But as it is now, the situation with `collections.` in TypoScript will not be changed - sorry!
