### ISSUE TITLE
field.inline.fal does not work when page and subpage has same page layout

### ISSUE THREAD

**Issue by joneppie** [FluidTYPO3/fluidpages#234]
Create a page-template with 
```
<f:section name="Configuration">
  <flux:field.inline.fal name="settings.picture" maxItems="1" />
</f:section>
```
Make sure that "Page Layout - this page" and "Page Layout - subpage" are the same and create new relation for one. After Saving the page, the relation is set for both, page and subpage, and one of them have a yellow exclamation mark.

**Comment by NamelessCoder** [comment]
I'm afraid we have to reject this one (and other similar issues with IRRE+FAL+FlexForms) as being problems with the TYPO3 core's way of handling this particular type of relation.

The technical reason for the problem is:

* IRRE FAL records are m:n and attach themselves to a field name.
* The field name used for this relation is the name of the FlexForm field when the IRRE FAL field is in a FlexForm (it is the name of the TCA field when it is not).
* The field names are the same in both your templates (because the field name is not dynamic and in both cases have the same value).

It is not technically incorrect for the core to handle the relation the way it currently does, but that being said, the handling could be improved a lot by *letting the TYPO3 core use not just the field name but the entire path to the field name*. E.g. if the field is called `myfield` and sits in a FlexForm object named `myobject` in a FlexForm section named `mysection` in a FlexForm TCA field named `root`, then the entire field name used for the relation might be `root.mysection.myobject.myfield`.

This would still not be the full solution (it still doesn't fix the problem with sections in FlexForms having only the location in the array as "ID", which means sorting objects in a section would cause relations that were added for item no. 3 to still be there for item no. 3 even if that object is no longer the same one). But it would be an improvement that would let IRRE FAL fields work better in the context of multiple FlexForm fields in the same record.

Please feel free to suggest this change to the core! It **is a breaking change** because there is no practical way to migrate the relations that will inevitably become invalidated.

**Comment by cweiske** [comment]
TYPO3 core bug created: [Bug #71239: FAL relation + flexform config: Use full setting path as name](https://forge.typo3.org/issues/71239).
