### ISSUE TITLE
flexform fields don't get removed when deleting a flux:field

### ISSUE THREAD

**Issue by janviehweger** [FluidTYPO3/fluidpages#263]
I'm not sure, whether this a bug or a feature. moreover i don't know if this issue belongs to fluidpages or flux itself. I'll just document on what problem I stumbled:

### Step 1. 
create a flux:input field with name `settings.exampleValue` in your fluidpage templates `Configuration` section, like this:
```
....
 <f:section name="Configuration">
    <flux:form id="mytemplate">
        <flux:field.input name="settings.exampleValue" default="0" label="exampleValue:" />
    </flux:form>
...
  </f:section>
...
```

and print it out in the `Main` section, like this:
```
<f:section name="Main">
The value of settings.exampleValue is: {settings.exampleValue} 
</f:section>
```

### Step 2.
go to a page in the typo3 backend, assign the page fluidpage template under `Page Layouts` ...

### Step 3. 
... and set the field `exampleValue` under `Page Configuartion` to a value, eg. 99. Save the page.

### Step 4.
in the typo3 frontend you should now see: 
```
The value of settings.exampleValue is: 99
```

also, check the field: `tx_fluidpages_layout`from the table `pages` for the page above. 
you should see a flexform like this: 

````
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3FlexForms>
    <data>
        <sheet index="options">
            <language index="lDEF">
                <field index="settings.exampleValue">
                    <value index="vDEF">99</value>
                </field>
            </language>
        </sheet>
    </data>
</T3FlexForms>
```
### Step 5.
repeat Step 3, and set a different value to  `exampleValue`, eg. 100

### Step 6.
repeat Step 4. The new value should be updated accordingly in the frontend and in the flexform. So far so good.

### Step 7.
remove the flux:input field from Step 1 and hit save.

```
....
 <f:section name="Configuration">
    <flux:form id="mytemplate">
    </flux:form>
...
  </f:section>
...
```
### Step 8.
repeat Step 3 & 4. You see the Problem? The value of `settings.exampleValue` seems to be still defined. A look into the flexform confirms it. The flexform still contains the definition for the deleted input field with the last assigned value, (here 100) Why this?

You may say - thats not a problem. If you dont't use the variable anymore, just don't care if it's still in the flexform. But wait. In my case this behavior has been a major problem, specialy when i tried to "externalize" the variable, like in Step 9:

### Step 9:
move the `settings.exampleValue`variable from the fluidpage template to the constants:

`constants.txt` in provider extension:
```
...
plugin.tx_myextension.settings{
   #cat=myextension/settings; type=int+; label=exampleValue
    exampleValue = 0
}
```
and `setup.txt`
````
...
plugin.tx_myextension.settings{
    exampleValue = {$plugin.tx_myextension.settings.exampleValue}
}
```

Then, in the constants field from the page above, set the `exampleValue` to a new value, by typing: 
````
plugin.tx_myextension.settings.exampleValue = 222
````
hit save and refresh the frontend. You may expect the new value of 222 gets displayed. But thats not the case. Still the old value of 100 is shown. If you look into the flexform, you see the same old value. 
What's the Problem here? 

### Workaround
The only workaround is to clear the whole flexform in the page record. By this the new value gets assigned. This helped in my case, but having many pages this can be very tough ...

Any ideas?

**Comment by janviehweger** [comment]
Maybe i found the solution by myself:

by setting `useTypoScript = 1` in the extensions `settings` object, the "old" value in the flexform get overridden by the one set by typoscript. Yeah!

Found this in the `initializeOverriddenSettings` method of the `AbstractFluxController` in `flux\AbstractFluxController.php`.

**Comment by NamelessCoder** [comment]
This is how FlexForms work in TYPO3. The only option that affects this is the "clean FlexForm XML" option which you can enable on a global level - and which you can trigger from the "lowlevel" extension, IIRC. The exact same thing would happen if you remove a field from a DS but the field was previously saved. The DB doesn't update when you update the template (step 7) and Flux won't by itself clean these leftover values. The TYPO3 core however, will, if you enable the flag to clean fields that no longer exist in the DS.

Be aware though that this also means you lose configuration when changing plugin types because TYPO3 will no longer store data if you change the DS. E.g. make a plugin a "news list" plugin and switch it to "news detail" and back, and you will have reset all the fields that don't exist in both DS'es.

Like you found out, you can use the TS/FlexForm transparency to at least override values that no longer exist in DS, giving them some backwards compatibility.

**Comment by janviehweger** [comment]
big thanks @NamelessCoder for the detailed explanation!

**Comment by NamelessCoder** [comment]
> b.t.w. - is there a way to override a value which has ben set via typoscript (with useTypoScript enabled) from a fluidpage template/page configuration value?

Yes and no. You'd have to choose another scope for the variable than `settings.` and you would have to add a condition that checks if one is set, else use the other. So not really an override, but an alternative which is protected from overriding by TS variable because it doesn't use the automatically merged `settings.` scope.

**Comment by NamelessCoder** [comment]
Please note that there are exactly two cases in which I would recommend **not** using the `settings.` scope. The above case is the one case - the other is when you prefix your field names with for example `tt_content.` and name the field along `tt_content.bodytext` when you want the value entered in your field to override the value in the root record, outside the FlexForm. All other cases should use `settings.` because of the transparency and automatic transferring of variables.
