### ISSUE TITLE
Page configuration values not inherited to backend page view.

### ISSUE THREAD

**Issue by lsoendergaard** [FluidTYPO3/fluidpages#276]
*Edit: when I say "backend page view" or "backend layout", I mean the place where you add your content elements (Backend -> Page)*

I'm on latest fluidpages development commit (d51c3f5). I'm also using fluidcontent, fluidcontent_core and flux development branches. TYPO3 version is 6.2.15.

What I'm trying to do: Having a value in the Page Configuration to determine the number of rows in the "Backend Layout". My Configuration essentially looks like this (frontend output is just iterating the same way and rendering columns, so not shown here):

```xml
	<f:section name="Configuration">
		<flux:form id="layout_frontpage" label="Startseite">
			<flux:field.input name="rowCount" label="Number of rows" default="1" />

			<flux:grid>
				<flux:grid.row>
					<flux:grid.column colPos="1" name="header" label="Header" />
				</flux:grid.row>

				<v:iterator.for from="1" to="{rowCount -> v:or(alternative: 1)}" iteration="iter">
					<flux:grid.row>
						<flux:grid.column colPos="{iter.cycle -> v:math.sum(b: 2)}" label="Content {iter.cycle}" />
					</flux:grid.row>
				</v:iterator.for>

				<flux:grid.row>
					<flux:grid.column colPos="2" name="footer" label="Footer" />
				</flux:grid.row>
			</flux:grid>
		</flux:form>
	</f:section>
```

This works fine for any page I explicitly set the value in my Configuration. The "Backend Layout" is displayed correctly with the correct number of rows and the frontend also outputs the same number of rows.

However.

If I'm on a subpage, and tell it to use the "Page Layout" of it's parent, the values are inherit correctly in the "Page Configuration" section and in the frontend, but not in the backend page view where the backend layout is supposed to show multiple rows. In fact, the "Page Configuration" values are not available at all in the page view if they are inherited (if I add `<f:debug>{_all}</f:debug>` to the Configuration section). Of course, if I set them explicitly in the subpage page, it works.

**Comment by NamelessCoder** [comment]
This case is about the only one that isn't possible to achieve because of a catch 22:

* In order to know which fields are inherited, we'd have to load the Form instance.
* In order to load the Form instance, we'd have to know which fields are inherited.

Because your Form's Grid "depends on itself" the only way you can get the result you need here, is to actually save the value in the FlexForm data directly, without inheritance. That way the first level variables can be assigned *before* retrieving the Form instance - but obviously won't contain inherited values because they are only first level variables.

Internally, inheritance works by scanning the form instance of the current record to determine which values are okay to inherit. Then, these inherited values are processed and turned into default values for any field that supports default values. And finally, when the record is saved, all values that are not changed (= inherited from the parent) are simply removed (from first-level variables). This means that you won't have access to your data in this exact location because it is inherited and thus removed from first-level variables. In other words: inside the `Configuration` section, no actual variables are inherited - merely field defaults are filled based on what is defined in the parent page.

And no, unfortunately you cannot access these default field values; at least not in a way that lets you use them in the `Configuration` section. Your fields will show the default values but they won't be stored in template variables.

Alternatives:

* Use TypoScript
* Disable inheritance on the field
