### ISSUE TITLE
Bring back "Paste as reference"

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/fluidpages#307]
Until version 3.0.0, fluidpages had a "paste as reference" button in the backend page view.
It was removed with version 3.1.0 in commit 6353dab98eba6fa3ebb981718d9f40f0bda85d21.

The functionality of this button is dearly missed by me. Please bring it back.

**Comment by cweiske** [comment]
Fluidcontent still has it:

![2016-04-20 fluidpages fluidcontent paste button](https://cloud.githubusercontent.com/assets/59036/14674703/92b35264-0705-11e6-85da-5c33b459ccb1.png)

**Comment by grimmcreative** [comment]
Missing this feature too. Thumbs Up

**Comment by NamelessCoder** [comment]
I'm sorry but this has to be rejected - the "paste as reference" feature will not come back, since we no longer override the parts of the PageLayoutView that would have allowed it to be brought back.

There is a fairly short process described on https://github.com/FluidTYPO3/flux/issues/1305#issuecomment-328512665 as alternative. I'm sure you both already know it, I'm just pasting it here for future reference :)
