### ISSUE TITLE
TYPO3 8.7 Release

### ISSUE THREAD

**Issue by Lumrenion** [FluidTYPO3/fluidpages#354]
Hi,

I am currently using the development branch of this extension as composer dependency and I could not find any errors using it with TYPO3 8.7 LTS yet.
So I wanted to ask, is there a scheduled date for merging development into master, and publishing a new version with TYPO3 8.7 LTS support? As I see it, it basically is supported, but the dependency in em_conf and composer.json tell a different story. Or am I missing something?

Thank you!
- Philipp

**Comment by Lumrenion** [comment]
Any updates on this?

**Comment by ogrosko** [comment]
Using typo3 v 8.7.2, flux 8.2.1, fluidpages 4.2.1

I'm getting following error when I want to access to page properties
`Call to a member function getOption() on null`

`Error thrown in file web/typo3conf/ext/fluidpages/Classes/Service/PageService.php in line 226.`

**Comment by NamelessCoder** [comment]
Everyone, if you could confirm that Fluidpages `dev-development` works on TYPO3 8.7+ (with and without Flux `dev-development` that would be great. I think we're ready for a release but need to catch any last minute problems since updating to match the Flux changes which drop 7.6 support.

Feel free to report on this thread if you find any issues, or create new bug reports if you're sure you found a bug.

**Comment by ogrosko** [comment]
Can confirm latest `dev-development` works fine with typo3 v8.7.2, flux v8.2.1 for now. I'll report a bug if I find some ;)

**Comment by oemmes** [comment]
I encountered a problem with the static tempalte being not available when "autoload" is off.

I created a pull request to fix it: #359

**Comment by NamelessCoder** [comment]
#359 merged, thanks for finding that one!

**Comment by ogrosko** [comment]
When I use config field for page:
`<flux:field.select name="fields.tags" items="{0:'Sold out'}" renderType="selectCheckBox" />`
I get following error when I save page:
`PHP Warning: strpos() expects parameter 1 to be string, array given in vendor/typo3/cms/typo3/sysext/core/Classes/DataHandling/DataHandler.php line 1719`

Using typo3 v 8.7.3, flux 8.2.1, fluidpages dev-development

**Comment by NamelessCoder** [comment]
@ogrosko If you only have a single option I suggest using the `checkbox` field type instead. You can add any number of checkboxes and name them for example `settings.tags.soldOut` and the resulting template variable becomes an array of those options that were selected. If for some reason you must use the `select` type you probably need to explicitly define your options as arrays of arrays, e.g. `<flux:field.select name="fields.tags" items="{0: {0: 'soldOut', 1: 'Sold out'}}" />` but I'd really not recommend adding a list of tags this way. The reason being that in order to check if a tag was set when you use this way, you'd need to implement an "does array contain" check instead of being able to simply check if `{fields.tags.soldOut}` is set.

Flux provides you with ample options to for example create a partial template with one tag field where you can use `f:render` to quickly generate many fields using actual checkboxes with individual names - for example based on an input array of name+label.

That said: Flux dev-development contains a fix to apply TCEForms wrappers where these were missing. If your use case is affected by that, updating to dev-development should solve the issue. But I still recommend switching strategies ;)

**Comment by sstorme** [comment]
Hello !
Is there a date of release to TER ?
Thanks !

**Comment by RozbehSharahi** [comment]
Im using fluidpages now on a live project 8.7.2 for some months (since lts release) without any big problems. Still installing typo3 8.7.2 as 8.6.99 to be able to install fluidpages. Three will always be bugs but it seems very compatible and usable for production to me.

**Comment by NamelessCoder** [comment]
Thanks for the feedback @RozbehSharahi - testing by aliasing packages is very helpful to determine if we're fully compatible ;)

**Comment by Kleisli** [comment]
I just discovered a problem concerning translations.

With the current development version, the tx_fed_page_flexform configuration is not supported in the pages_language_overlay records.

Step 1 is to add this configuration to pages_language_overlay TCA for tx_fed_page_flexform and tx_fed_page_flexform
`'behaviour' => [
	'allowLanguageSynchronization' => true
]`

In my installation this works fine, but only if there is only one flux.field of type flux:field.relation, but for fields of type flux:field.input, when I select "Value of default language", it takes the whole xml string of the field tx_fed_page_flexform as value for the localized input field. 

according to the docs, the option should also be working for flex fields.. 
https://docs.typo3.org/typo3cms/TCAReference/8-dev/ColumnsConfig/Type/Flex.html#behaviour

**Comment by cweiske** [comment]
Since no commits came in the last months, releasing the current state for 8.7 in TER would really be appreciated.

**Comment by oft-test-account** [comment]
Hello,

I was wondering, if there is going to be a release for Typo 8.7? Are there any plans for putting the latet version in TER?
Thanks in advance!

**Comment by Ben305** [comment]
Can somebody release this for TYPO3 8.7?

**Comment by coding46** [comment]
@NamelessCoder What do we need to fix / to do to get a 8.7 LTS compatible TER version released.

**Comment by JostBaron** [comment]
This became more urgent with the release of Ubuntu 18.04 LTS, which ships with PHP 7.2. The current released version is not compatible to PHP 7.2.

**Comment by dahaupt** [comment]
@NamelessCoder Thanks for your work in the past days to create an release for us with official support for TYPO3 8.7. I think we can finally close this one.
