### ISSUE TITLE
Impossible to recover settings from page_language_overlay

### ISSUE THREAD

**Issue by filoucrackeur** [FluidTYPO3/fluidpages#360]
flux 8.4 fluidpage 4.1.0

I'm trying to recover my translated data from fluidpages in my fluid view and i only recover data from origin language page

Can you verify that in default language
**settings.toto = blabla** 

in alternative language page 
**settings.toto = blabla [translated]**

i recover everytime **{settings.toto}**    ===> blabla 

It does not matter de language of my page

**Comment by NamelessCoder** [comment]
Please retry this with `dev-development` of Fluidpages. https://github.com/FluidTYPO3/fluidpages/commit/a9441ee9c0897cb3cf840859cc03fe3ce5ae74c9 may very well have fixed this.

**Comment by filoucrackeur** [comment]
Uncaught TYPO3 Exception
Class 'TYPO3\CMS\Fluid\View\TemplatePaths' not found 

Error thrown in file
/home/DE/pcourt/dev.sunshine.qua/web/typo3conf/ext/fluidpages/Classes/Provider/PageProvider.php in line 155.

When i use it

**Comment by rsternec** [comment]
I got the same error with current dev-development:

Uncaught TYPO3 Exception
Class 'TYPO3\CMS\Fluid\View\TemplatePaths' not found

TYPO3 7.6.20
PHP 7.0.7
flux 8.2.1

**Comment by NamelessCoder** [comment]
`dev-development` of Fluidpages (and Flux) has dropped 7.6 support so it's natural you experience errors on those. Sorry, I should have mentioned this, but you didn't say you were on 7.6. You'll need to confirm this on TYPO3 8.7 and if not solved there, we'll look into it.

A new legacy branch will be made at some point, which you should switch to - and after that you are invited to cherry-pick the fixes you want and open PRs to that branch.

**Comment by filoucrackeur** [comment]
Yes sorry i don't mentioned my TYPO3 version 7.6 it's correct

**Comment by mrwhy-orig** [comment]
I made an update of an old Typo3 6.2 page to Typo3 8.7 with flux 8.2.1 and fluidpages 4.1.0

Unfortunately i encountered the same error. I just get the untranslated content in the frontend.

Then i changed the line of code like in #a9441ee and i get the translated fields. Anyway, there is no fallback if any field isn't translated. 
(Unfortunately the development branches aren't working in my installation. I will submit a seperate issue on this.)

**Comment by filoucrackeur** [comment]
thanks a lot for your feedback maybe a patch will be a good idea ?

**Comment by mrwhy-orig** [comment]
I read a few more issues on this and I'm afraid my expected functionality was removed. Am I right @NamelessCoder ? With #349 the merging of untranslated fields has been droped.

**Comment by NamelessCoder** [comment]
I will close this issue since TYPO3 7.6 is no longer supported.

@mrwhy-orig

> I read a few more issues on this and I'm afraid my expected functionality was removed. Am I right @NamelessCoder

Yes, that is correct. Two related features were removed: FlexForms themselves no longer support combining multiple languages inside the same data storage, this was removed in TYPO3 itself and will definitely not be restored. The other removal was the merging of configuration from `pages_language_overlay`, but this entire table will be gone in TYPO3v9 where the translated pages will simply be stored in `pages` with a different language UID.

> I would really much appreciate to bring it back.

I'm afraid that will not happen, but Flux provides you with a way to manually read the original data set and VHS contains a ViewHelper that allows you to merge those - so at least, you'd be able to use translated settings when rendering the values. You'll need:

* `flux:form.data` with table and field parameters, and uid parameter taken from the translated page properties' column containing translation parent's UID.
* `v:iterator.merge` to merge the two data sets.
* For convenience, `f:variable` or `v:variable.set` to declare those as intermediate variables you can pass around.

The good thing about this approach, though it's more complex than having Fluidpages do it for you, is that it will transparently work the same on TYPO3v8 and v9 because the way of targeting the original record is the same and the changes in the language overlaying do not affect how the method works.
