### ISSUE TITLE
PageController does not pass ControllerContext "pluginName" to View

### ISSUE THREAD

**Issue by Schweriner** [FluidTYPO3/fluidpages#364]
PHP 7.1
TYPO3 8.7.4
fluidpages 4.1
flux 8.2.1

As mentioned above, the ControllerContext of the View-Object of PageControllers is missing the correct pluginName "page". This will cause a bad behavior when using Widget-ViewHelpers inside the Fluidtemplate of "Page". Links generated by Widget-Viewhelpers that are using widget.link / widget.uri to create widget-urls will create urls like tx_providerextension_[@widget_0] instead of tx_providerextension_page[@widget_0]

**Comment by Schweriner** [comment]
A possible solution would be adding a function setPluginname to ViewContext which should set the correct pluginname in the PageProvider class inside the getViewContext function.

**Comment by ilomedia** [comment]
+1 i can confirm this behavior and this is kind of blocking for me, any plan on this?

**Comment by NamelessCoder** [comment]
This should no longer be an issue; Flux will indiscriminately assign the exact ControllerContext that the controller received from TYPO3. If you still face problems along these lines please report that to the [Flux bug tracker](https://github.com/FluidTYPO3/flux/issues) since Flux is responsible for initialising this controller class.
