### ISSUE TITLE
backend-layout is empty when fluidcontent isn't installed

### ISSUE THREAD

**Issue by TheNaderio** [FluidTYPO3/fluidpages#374]
Hi,
at first: I have installed fluidpages,(fluidcontent), flux, vhs all in the latest dev-build from github.

I thought fluidcontent is obsolete and tried to use fluidpages standalone with TYPO3 8.7.9 .

When I install fluidcontent, everything in the backend shows up correctly. But when i disable it, i got a "blank" page (the Page title shows up, so it is not a dead page).

Is there something I need to consider when using fluidpages standalone?

EDIT:
When go to "Page configuration" while fluidcontent NOT installed it shows "**Data Structure ERROR: No ['ROOT']['el'] element found in flex form definition.**"
![image](https://user-images.githubusercontent.com/25088164/35355413-872e51a2-014d-11e8-96f8-882907bc2df9.png)

**Comment by koehlersimon** [comment]
I have the same problem now and it seems that only the developers of fluidpages / fluidcontent know how to run the system.! Too bad, gonna switch to Gridelements I think. What a mess, 2 days of work for nothig. Did you succeed btw.??

**Comment by koehlersimon** [comment]
@NamelessCoder do you have an idea about this? I don't mind hiring you for helping out, since our project is pretty serious and important. We need to fix this soon, otherwise we will decide to throw it all away and use gridelements wich is not the preferred but maybe the more stable solution.

**Comment by NamelessCoder** [comment]
@koehlersimon I don't mind helping but I am quite overbooked, so the following hints will have to do. Hopefully that solves it - if not, you may be able to get assistance, paid or not, from contributors like @glucka or @BenjaminBeck who are quite comfortable with the setup process. All of this assumes you use v9 of Flux:

1. If this is an old site, make sure you migrate your templates first of all. If they use flux:grid.column then you must add a colPos argument with value between 0 and 99, also for content templates.
2. Once this is done, run the migration script in EM which migrates your records.
3. In whichever pages where you selected a "backend_layout" value, make sure you change the selection. The identifier for the Fluidpages layout is now different.
4. Make sure you selected a template to use for this and sub-pages in the "Page Layouts" tab. Briefly explained: "backend_layout" needs to be set to Fluidpages' identifier so the BE layout columns work - and "Page Layout" needs to be set so the FE output will render the right page template.
5. Once both are changed, and assuming template files are valid, you should see your form elements in "Page Configuration" and the grid structure you declared, if any, in the page module. If you don't use Fluidpages' grid columns disregard the info about "backend_layout". Use whichever method you desire :)

And don't forget: if you do locate a bug and that's the reason for this problem, investigating and solving it may be much cheaper than migrating to another extension base. I can promise that if you're willing to follow bug fixes up with things like fixing failing tests, your patches can get merged with record speed and there won't be as long between releases as there has been.

**Comment by koehlersimon** [comment]
Thanky for your reply. I did all that already so unfortunately nothing more I can do. The error message says: "Data Structure ERROR: No ['ROOT']['el'] element found in flex form definition." See Screen above. Doesn's that simply mean the Flexform XML is not valid? Where is this flexform generated? For me it means the Flexform has been loaded but has kind of syntax errors. I am still not getting it working. I will now finally take a look into your code to find the bug. For me it looks like a bug.

**Comment by NamelessCoder** [comment]
Did you enable the form compacting feature in EM config (it's broken, will be removed)? Or did you set `compact` option in the Flux form? If so, remove those.

**Comment by koehlersimon** [comment]
None of the options was selected. Still not working. I can not select "Fluidpages" in the backend_layout, but "FluidTYPO3.Flux" appears in the select menu as the only option. Under "Page Layouts" the selects are empty. Everything worked before, I did not create any new templates. Error message from above appears. I have searched your codes but I can not find where the error is coming from. So we are at the point now to think about a custom solution for our project instead of using any existing extension. Why don't you make a paid project of it? I am sure it would make it. I would buy and support it when it will be 100% supported.

**Comment by NamelessCoder** [comment]
It kind of sounds like you registered elements as if they were part of the Flux extension (using Vendor.ExtensionName `FluidTYPO3.Flux`. Normally you would never see this as an option to select in the `backend_layout`. Perhaps you registered the provider extension incorrectly? It needs to use your own identity.

You can check https://github.com/FluidTYPO3/flux/files/2197422/test-provider-extension.zip for reference. Extract it, rename the folder to `testing` and place in `typo3conf/ext` then enable in EM. Load the static TS in your root template.

![screen shot 2018-08-15 at 11 38 47](https://user-images.githubusercontent.com/2228052/44142261-05b78e2c-a080-11e8-9c4f-0813f69d5f20.png)

![screen shot 2018-08-15 at 11 39 07](https://user-images.githubusercontent.com/2228052/44142272-09479816-a080-11e8-985e-6904a0baed6a.png)

Then if you wish, put a single field in the `Templates/Page/Standard.html` file and that should appear in "Page Configuration". For example `<flux:field.input name="test" label="Test" />`.

Still doubtful:

1. I do not think this has anything to do with fluidcontent being installed or not. However, when you install or uninstall this extension it does clear the caches so that could be part of the explanation.
2. Flux would deliver a default DS which prevents that warning you mention, if only the selection values shown in the screenshot are correct. Note that what these values are, also depends on your chosen vendor + extension name when you register the provider extension.

> I have searched your codes but I can not find where the error is coming from.

It comes from TYPO3 itself, because TYPO3 receives a data structure array when reading the FlexForm DS, and that array as the message mentions lacks a critical element. There could be multiple reasons why that happens - and they include possibly having other extensions installed that do things with FlexForms. But the more likely reason based on your information above, seems to be the registration of the provider extension was not made correctly (uses our vendor and ext key, not your own).

> Why don't you make a paid project of it? I am sure it would make it. I would buy and support it when it will be 100% supported.

Thanks for the words of support - but there is near zero chance that FluidTYPO3 will become a paid project or even provide some paid components and others free. I am very against two-tier user systems in FOSS which is why I only sell my time and knowledge, not licenses ;)

**Comment by koehlersimon** [comment]
Thanks for the detailed answer again! Everything is correctly configured, double checked it all, and there are no other third party extensions.

Question: Did you ever try to install your test provider ext in a TYPO3 8.7.18 ? It just crashes everything, backend and frontend, because of a template that can not be found but of course it exists. Provider extension says "compatible with 8.6" version of TYPO3, so I guess you have never tested it with 8.7. or yes?

I will give it another try of a few hours today, but then I'll give it up. Way too dangerous for the future. Yes, I understand beeing against payed software. But the problems of free software are clearly visible here. Developers have no time for support or bugfixing, no clear documentation (the whole TYPO3 project), and in the end it is not cheaper at all for the client, because of all that bugfixing and the service provider being more a bugfixer than a creator.

Will try to put your provider ext and my ext in a fresh install and see what happens then...

I knew that the error message mentioned above comes from TYPO3, but I don't think TYPO3 produces it. I found this and the "<ROOT><el>" section exists. Maybe this is beeing overwritten somewhere?

**Comment by NamelessCoder** [comment]
> Did you ever try to install your test provider ext in a TYPO3 8.7.18 ?

Tested it, and the Flux v9 revision, on 8.7.16 I believe it was. Have not repeated tests since.

It contains one intentionally broken template (for a WIP feature). You may need to delete the "Section objects as containers" content element.

> Developers have no time for support or bugfixing

I mean no offence but that's not really fair given you've just received ~1.5 hours of free support from an extension creator mere hours after posting your comment. It's not like we don't take time to help. And sometimes for free! ;)

**Comment by TheNaderio** [comment]
I dont tested the test_provider_extension in 8.7.x but i am actually running multiple sites with flux and fluidpages and **without fluidcontent**.

Can you provide your extension (of course cleaned of sensitive data)? 
I'd like to look at your problem, because I think it's fixable.

**Comment by NamelessCoder** [comment]
> I offered you payment, you said you are overbooked and still spend your time.

Sure - I don't need you to pay for this time. The information I thought could be useful to others so I made the time during lunch breaks, inbetween tasks, while cooking, etc.

> I personally have never published even one of the hundreds of extensions I have developed, because I don't want people to have problems with my codes and then I can not help them and need to tell them everything is for free

Just on a personal note, if you ask me that's a damn shame. Think of all the input you've missed. That's the trade we make - improvements and suggestions in return for sometimes answering questions or making fixes you don't need yourself. Doing that is part of the reason why my skills are where they are ;)

Aaaanywho: if you don't mind waiting until mid-September I could offer you a couple of days where I play detective with your project! I didn't mention that at first because you said you were in a hurry.

**Comment by koehlersimon** [comment]
Ok I just installed the "testing" provider EXT in a different TYPO3installation with version 8.7.15 where none of my own extensions was installed. The same error with the wrong Flexforms like mentioned above appears. Also "FluidTYPO3.Flux" appears in the select menu for the backend_layout. That's it so far FYI.

Thanks a lot for your time, I don't have more of it now, need to find another solution for this project.

**Comment by koehlersimon** [comment]
Thank you @NamelessCoder for all your time again. I figured out how it works now. Don't ask me how, I have no idea with all these dependencies it's hard to find the problem sometimes. A TYPO3 typical thing, you get it runnung and don't know exactly how. I think in the end it was a caching / autoload problem and nothing more. I was stressed and maybe I forgot something.

Anyway I would like to do a big thing with fluidpages and flux, and I decided to support the whole project now. Financially and practically. I have tons of templates for custom content elements and bootstrap components, will publish them soon.

But there are also some little bugs I have found, I will report here, okay?
Since I currently work like 8 hrs a day with fluidpages/flux, I get some deeper experience with it.
Greatest thing that has been developed for TYPO3 ever, in my opinion.

Thank you and sorry If I was a bit annoying here ;)

**Comment by NamelessCoder** [comment]
> caching / autoload

We've all been there before and it won't be the last time ;)

> Anyway I would like to do a big thing with fluidpages and flux, and I decided to support the whole project now. Financially and practically.

Sounds good! I welcome the support, whether it's financial or in the form of bug fixes. If you have something specific in mind don't hesitate to get in touch. Bug reports of course go on GitHub and do keep them coming - but if you're thinking about a feature to help integrate larger collections, we can always discuss the use case and possible solutions that might fit as sponsored work.

> Greatest thing that has been developed for TYPO3 ever, in my opinion.

Wow, that's high praise. Thanks! Always happy to hear when people find it useful!

> Thank you and sorry If I was a bit annoying here ;)

You're welcome and don't worry. I've also been on the other end of similar frustrations. The outcome was good and that's what counts - and for sure it sounds like you'll be moving a lot faster onward now. As always, if you've got questions about Flux API, just ask!

**Comment by TheNaderio** [comment]
That's a good turn of the initial conversation :)

On the issue itself, I think it can be closed, because the error definitely no longer exists.

**Comment by JPDesign** [comment]
@X-Tender 
Check your php.ini and change:
max_execution_time = 30
30s is verry short.
Set
max_execution_time = 60
or more

**Comment by X-Tender** [comment]
Then I get the error after 60 (or more) seconds.

**Comment by X-Tender** [comment]
Ok I got the issue, I just had to click "save" on the page properties Page. I've just seen the error and started to search for the issue. 🤪
After "save" the Tab disappeared and the page loaded .

**Comment by ocjojo** [comment]
For me this is happening with Typo3 9.5.5, Flux 9.2.0 and Fluidpages 5.0.0
It's not really a problem, but having an error message is still not nice.

I narrowed it down. If you do not provide any fields in the Page Template e.g.
```xml
<f:section name="Configuration">
    <flux:form id="standard">
    </flux:form>
    <flux:grid>
      <!-- Edit this grid to change the "backend layout" structure -->
      <flux:grid.row>
        <flux:grid.column colPos="0" name="main"/>
      </flux:grid.row>
    </flux:grid>
  </f:section>
```
Then in `flux/Classes/Provider/AbstractProvider.php: L775` it builds a default form, which is defined in `fluidpages/Configuration/TCA/Overrides/pages.php: tx_fed_page_flexform`
This is supposed to have an empty array "el". But instead it returns an empty string `'el' => ''`.

I am not sure if this is a bug in typo core or should be checked for in flux.

Anyhow, to make the error disappear, I included a conditional field that is not shown:
```xml
<flux:field.input name="settings.placeholder" displayCond="FIELD:settings.placeholder:=:1" />
```

**Comment by dipakCrayon** [comment]
What is the meaning of displayCond="FIELD:settings.placeholder:=:1"  condition ?

**Comment by X-Tender** [comment]
@dipakCrayon
It's a display condition and say that the element is only shown when settings.placeholder have the value 1. In this case it's checked and because it's initially not checked its never shown. 
Don't know what I have to think about the workaround ☺

**Comment by dipakCrayon** [comment]
**@X-Tender** 
Thanks for your replay.

**Comment by cweiske** [comment]
I had the same problem as the issue reporter:
- Page properties > Appearance > Backend Layout had "FluidTYPO3.Flux"
- Page properties > Page layouts > Page layouts is empty

The reason for that in my case was that TYPO3 had automatically disabled my provider extension during the upgrade from TYPO3 v7 to v8 because the extension's ext_emconf.php said it's only compatible with TYPO3 v7.
