### ISSUE TITLE
Field tx_fed_page_controller_action gets an empty value

### ISSUE THREAD

**Issue by imiMscherer** [FluidTYPO3/fluidpages#377]
When saving page properties on the backend the DB field "tx_fed_page_controller_action" gets an empty value (before saving the value is "siteprovider->Contentpage"). The result is, no BE Layout is shown and no content will be rendered.

Version 4.1.0
TYPO3 7.6.24

**Comment by NamelessCoder** [comment]
Related: https://github.com/FluidTYPO3/fluidpages/commit/c8be6c3a5df6781c917cb334f6d3e4f28e18a1ce

A template must be selected, though, or fluidpages will attempt to render one called "Default" which may or may not exist, depending on your exact site setup. FYI, if the value is `extkey->Somevalue` that points to possibly two things being wrong:

1. Very likely you configured the extension identity as `extension_key` instead of the proper `Vendor.ExtensionName` format - this can be in your `ext_localconf.php` file or in template files.
2. Very unlikely you have a custom Provider class which is returning the wrong value from `getControllerExtensionName`.

PS: you really, really should update your TYPO3 version! Future releases of Fluidpages and Flux will not support the one you're on.
